import streamlit as st
import pandas as pd
import random

st.set_page_config(page_title="Ohio RE: Unit 2 Master", layout="centered")

# 1. DATA INITIALIZATION
if 'cards' not in st.session_state:
    quiz = [
        {"q": "1. Real estate generally includes all the following EXCEPT:", "opts": "a. trees.\nb. air rights.\nc. annual crops.\nd. mineral rights.", "ans": "c. annual crops.", "exp": "Annual crops (emblements) are personal property."},
        {"q": "2. A woman rents space in a commercial building for a bookstore... Which BEST characterizes the contents?", "opts": "a. The shelves and tables are trade fixtures and will transfer when the owner sells.\nb. The shelves and tables are trade fixtures and may properly be removed by the woman before her lease expires.\nc. Because the woman is a tenant, the shelves and tables are fixtures and may not be removed.\nd. Because the shelves and tables are attached, they are treated the same as other fixtures.", "ans": "b. The shelves and tables are trade fixtures and may properly be removed...", "exp": "Trade fixtures belong to the tenant and are removable."},
        {"q": "3. The term nonhomogeneity refers to:", "opts": "a. scarcity.\nb. immobility.\nc. uniqueness.\nd. indestructibility.", "ans": "c. uniqueness.", "exp": "No two parcels of land are exactly the same."},
        {"q": "4. Another term for personal property is:", "opts": "a. realty.\nb. fixtures.\nc. chattels.\nd. fructus naturales.", "ans": "c. chattels.", "exp": "Chattel = Personal Property."},
        {"q": "5. A property owner wants to use water from a river... state relies on which rule of law?", "opts": "a. Riparian rights\nb. Littoral rights\nc. Doctrine of prior appropriation\nd. Doctrine of highest and best use", "ans": "c. Doctrine of prior appropriation", "exp": "Water use is controlled by the state via permits."},
        {"q": "6. A man inherited vacant land, removed topsoil, and died. Which is TRUE?", "opts": "a. Daughter inherits nothing.\nb. Daughter inherits the property as is.\nc. Daughter owns the topsoil wherever it is.\nd. Estate must restore property.", "ans": "b. The daughter inherits the property as is.", "exp": "She inherits the remaining interests in the land."},
        {"q": "7. A court would NOT consider which of the following for fixture status?", "opts": "a. The cost of the item\nb. Removal damage\nc. Adaptation to real estate\nd. Agreement of parties", "ans": "a. The cost of the item when it was purchased", "exp": "Cost is not part of the MARIA fixture test."},
        {"q": "8. Which is a physical characteristic of land?", "opts": "a. Indestructibility\nb. Improvements\nc. Area preference\nd. Scarcity", "ans": "a. Indestructibility", "exp": "Physical traits: Immobility, Indestructibility, Uniqueness."},
        {"q": "9. Act by which real property can be converted into personal property:", "opts": "a. Severance\nb. Accession\nc. Conversion\nd. Attachment", "ans": "a. Severance", "exp": "Severance involves detaching an item (e.g., cutting a tree)."},
        {"q": "10. Seller took a ceiling fan not addressed in the contract. Which is TRUE?", "opts": "a. Ceiling fans are usually considered real estate.\nb. The fan belongs to the seller.\nc. Fans are trade fixtures.\nd. Fans are personal property.", "ans": "a. Ceiling fans are usually considered real estate.", "exp": "Fixtures stay with the real property."},
        {"q": "11. Buyer sold mineral rights to an oil company. Buyer gave up:", "opts": "a. Air rights\nb. Surface rights\nc. Subsurface rights\nd. Occupancy rights", "ans": "c. Subsurface rights", "exp": "Mineral rights are beneath the surface."},
        {"q": "12. Lumber in the driveway for building a porch is:", "opts": "a. real property.\nb. personal property.\nc. a chattel that is real property.\nd. a trade fixture.", "ans": "b. personal property.", "exp": "Unattached building materials are personal property."},
        {"q": "13. Annexation, adaptation, and agreement are legal tests for:", "opts": "a. trade fixtures.\nb. real estate.\nc. a fixture or personal property.\nd. an improvement.", "ans": "c. a fixture or personal property.", "exp": "The MARIA test determines fixture status."},
        {"q": "14. Parking spaces and water rights are classified as:", "opts": "a. covenants.\nb. emblements.\nc. chattels.\nd. appurtenances.", "ans": "d. appurtenances.", "exp": "Appurtenances run with the land."},
        {"q": "15. A company builds tin shacks for turpentine storage. Which is TRUE?", "opts": "a. Action constitutes improvement.\nb. Chemicals are appurtenances.\nc. Shacks are trade fixtures.\nd. Use not in bundle of rights.", "ans": "a. The company's action constitutes improvement...", "exp": "Artificial attachments are improvements."},
        {"q": "16. Land located along the banks of a river. Water rights are:", "opts": "a. littoral rights.\nb. prior appropriation rights.\nc. riparian rights.\nd. hereditaments.", "ans": "c. riparian rights.", "exp": "Riparian = Flowing water (Rivers)."},
        {"q": "17. Bundle of rights entitles owner to all EXCEPT:", "opts": "a. sell property.\nb. exclude utility meter readers.\nc. erect No Trespassing signs.\nd. enjoy profits.", "ans": "b. exclude utility meter readers.", "exp": "Utility companies have access via easements."},
        {"q": "18. According to law, a trade fixture is usually treated as:", "opts": "a. a fixture.\nb. an easement.\nc. personalty.\nd. a license.", "ans": "c. personalty.", "exp": "Personalty is another term for personal property."},
